name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # The branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the Node.js version required for your project

    - name: Install dependencies
      run: npm install
      working-directory: ./  # Specify the directory where package.json exists

    - name: Build
      run: npm run build
      working-directory: ./  # Specify the directory where package.json exists

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.RS_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
